### ISSUE TITLE
Problème d'affichage avec un compte Google spécifique

### ISSUE THREAD

**Issue by faussetune** [mchev/blinest#100]
Bonjour,

Lorsque je visite le site Blinest, celui-ci ne s'affiche pas correctement et certains éléments sont manquants lors des blind-tests. Par exemple, je ne vois pas les boutons pouce rouge/vert pour évaluer les chansons, la barre de recherche en haut de la page d'accueil est absente, et le site met un temps considérable à charger. J'utilise Google Chrome avec plusieurs comptes et j'ai remarqué que ce problème est spécifique à un compte Google en particulier, quel que soit l'ordinateur utilisé. Pour résoudre ce problème, je dois changer de navigateur ou utiliser un autre compte Google (voir photos de comparaison ci-jointes). Je précise que je parle du compte utilisé pour me connecter à Chrome, et non du compte Blinest.

Bien que je sois conscient que ce problème vient de mon côté, je n'arrive pas à en identifier la cause. J'ai essayé de vider l'historique et le cache de ce compte Google, d'accepter les cookies, et de désactiver toutes les extensions pouvant causer des interférences, mais sans succès. Peut-être auriez-vous une solution à me proposer, même si ce problème ne relève pas directement de votre ressort ?

Merci d'avance et bonne journée !

![Blinest interface normale](https://github.com/mchev/blinest/assets/171011782/e955d292-81aa-4c43-81e8-87eb4b35c368)
![blinest interface bug](https://github.com/mchev/blinest/assets/171011782/e13b6d88-bfef-4dc6-b46b-e0eeb8342d1b)

**Comment by mchev** [comment]
Bonjour,

Le premier truc qui me vient à l'esprit c'est que ce compte a peut être une extension activée qui bloque certain contenus.
Un adblocker ou autre.
On dirait que ça bloque les éléments de formulaire, type button, input, etc.

Sinon il est possible que le compte soit associé à un Workspace ou autre qui a des policies stricts (un compte boulot): 
https://support.google.com/chrome/a/answer/2657289?hl=en#zippy=%2Cpolicies-set-for-users

**Comment by faussetune** [comment]
Bonjour, merci pour ta réponse ! J'ai désactivé toutes mes extensions et j'en ai même désinstallé, mais rien n'y fait.. Mon compte n'est pas associé à un workspace non plus. Honnêtement, j'arrive à jouer et ça ne me pose pas de problème mais c'est sûre que je préfère l'expérience complète. Merci quand même !

**Comment by faussetune** [comment]
Peut être que cela peut aider, voici les extensions que je possède, Adblock est désactivé et mon abonnement NordVPN est terminé
![Capture d'écran 2024-05-28 121109](https://github.com/mchev/blinest/assets/171011782/088c3f60-a4a3-4849-bd21-55a3f5445bad)
 j'ai également shazam en extension (non montré sur le screenshot)

**Comment by mchev** [comment]
> Peut être que cela peut aider, voici les extensions que je possède, Adblock est désactivé et mon abonnement NordVPN est terminé ![Capture d'écran 2024-05-28 121109](https://private-user-images.githubusercontent.com/171011782/334365043-088c3f60-a4a3-4849-bd21-55a3f5445bad.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcxMzg2MzEsIm5iZiI6MTcxNzEzODMzMSwicGF0aCI6Ii8xNzEwMTE3ODIvMzM0MzY1MDQzLTA4OGMzZjYwLWE0YTMtNDg0OS1iZDIxLTU1YTNmNTQ0NWJhZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUzMVQwNjUyMTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MzE2YmIzOWExYWZmOTE5M2Y1MWM4Njg1NjIxODhkZjA2NDViOTBkOTQ5Y2NjMTVjNWI5MzQ3YWZjZjk1NDE1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.xUjrkVboIgC96xoh3Chp7n01RTdfcPY5PAXqHi2v6SU) j'ai également shazam en extension (non montré sur le screenshot)

Si tu dis que tu as essayé en désactivant toutes les extensions, ça doit venir d’ailleurs.
- Il faudrait essayer de réinitialiser les paramètres du compte.
- Si possible voir si il y a des messages d'erreur dans la console en allant sur le site.
- ça ne le fait qu'avec Blinest?

**Comment by faussetune** [comment]
> > Peut être que cela peut aider, voici les extensions que je possède, Adblock est désactivé et mon abonnement NordVPN est terminé ![Capture d'écran 2024-05-28 121109](https://private-user-images.githubusercontent.com/171011782/334365043-088c3f60-a4a3-4849-bd21-55a3f5445bad.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcxMzg2MzEsIm5iZiI6MTcxNzEzODMzMSwicGF0aCI6Ii8xNzEwMTE3ODIvMzM0MzY1MDQzLTA4OGMzZjYwLWE0YTMtNDg0OS1iZDIxLTU1YTNmNTQ0NWJhZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUzMVQwNjUyMTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MzE2YmIzOWExYWZmOTE5M2Y1MWM4Njg1NjIxODhkZjA2NDViOTBkOTQ5Y2NjMTVjNWI5MzQ3YWZjZjk1NDE1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.xUjrkVboIgC96xoh3Chp7n01RTdfcPY5PAXqHi2v6SU) j'ai également shazam en extension (non montré sur le screenshot)
> 
> Si tu dis que tu as essayé en désactivant toutes les extensions, ça doit venir d’ailleurs.
> 
> * Il faudrait essayer de réinitialiser les paramètres du compte.
> * Si possible voir si il y a des messages d'erreur dans la console en allant sur le site.
> * ça ne le fait qu'avec Blinest?


Merci pour votre réponse ! En effet, je rencontre ces problèmes uniquement avec Blinest, et seulement sur Google Chrome avec mon compte Google. Lorsque j'ai essayé sur Firefox, l'affichage s'est correctement effectué. J'ai également remarqué des messages d'erreurs dans la console, mais je ne sais pas comment les résoudre.

![image](https://github.com/mchev/blinest/assets/171011782/b815fa3c-9d3d-4325-946b-bf410f06f8b0)

Je dois avouer que j'ai peur de perdre des données importantes si je réinitialise les paramètres de mon compte Google, donc je préfère garder cette option en dernier recours. Si le problème est trop complexe à résoudre, je préfère laisser les choses telles quelles.

Merci !

**Comment by Numb25** [comment]
Hello, j'ai le même problème avec mon compte associé à un compte gmail et via le pc.  Chargement des pages hyper lent, je suis obligée de rafraichir la page après sélection pour pouvoir entrer dans une room.  Cela fonctionne pourtant bien via le tel. Par contre, que ça soit firefox ou Google Chrome, ça ne change rien, sur pc c'est très lent.

**Comment by mchev** [comment]
C'est corrigé
