### ISSUE TITLE
Partie qui ne se lance pas dans une room

### ISSUE THREAD

**Issue by ValGallagheer** [mchev/blinest#104]
Bonjour,

Depuis hier, lorsque je veux relancer une partie après avoir jouer, rien ne se passe, aucune partie ne se lance.

**Comment by mchev** [comment]
Bonjour, merci pour le retour. Le bug est connu et devrait être résolu dans la semaine prochaine.
En attendant, normalement il suffit de rafraichir la page pour relancer une partie.

**Comment by ValGallagheer** [comment]
Bonjour,

Malgré le rafraîchissement de la page impossible de lancer une partie.
Mais je vais attendre que le bug soit résolu.

**Comment by mchev** [comment]
C'est corrigé
