### ISSUE TITLE
Nouvelle police du chat/interligne

### ISSUE THREAD

**Issue by Numb25** [mchev/blinest#105]
Bonsoir, 
La nouvelle police du chat est beaucoup trop petite (et interligne plus serré ?).
Ce n'est pas très facile à lire :( 
Est-ce qu'il y a possibilité de revenir à l'ancienne police/interligne ?
Merci d'avance :)

**Comment by mchev** [comment]
Je me suis basé sur la taille de police d'un des outils du même type les plus utilisés : twitch

Je peux augmenter un petit peu..

**Comment by Numb25** [comment]
C'est super maintenant, merci bcp ! plusieurs s'étaient plaints hier... (on n'a plus de très bons yeux lol)
et cool pour les emojis de retour aussi ! 
Encore merci :)
