### ISSUE TITLE
plays dénigrantes sur les autres joueurs

### ISSUE THREAD

**Issue by Numb25** [mchev/blinest#106]
Un joueur déjà banni par le passé (et qui a créé plusieurs comptes également bannis) s'amuse à créer des plays dénigrantes vis à vis de certains joueurs.  Ces plays sont toujours visibles.  Est-ce qu'il y a moyen de les supprimer ?
Par ailleurs, certains noms de plays sont vraiment grossiers... autant sur le chat il y a une censure, autant pour le nom des plays, tout est accepté.  On sait faire quelque chose pour ça ?
Merci

**Comment by mchev** [comment]
Merci pour le retour. Est ce que cela a été signalé auprès des modérateurs ?
Je veux bien le nom du joueur ou au moins un nom de playlist pour que je retrouve l'origine. (En privé sur discord c'est mieux)
