### ISSUE TITLE
Clicking on my room brings me to the Quiz Général room

### ISSUE THREAD

**Issue by Mishatje** [mchev/blinest#16]
Hi/Bonjour,

When I try to join one of my rooms on the main page, it brings me to the general room. Same thing happens when I create new rooms.
Is there a way to fix this, or is it a bug on the site itself?

Thank you.

**Comment by mchev** [comment]
Salut, ce n'est n'est pas normal effectivement. Est ce que tu pourrais me donner l'url de ta room pour que j’essaie de reproduire le problème?

**Comment by Mishatje** [comment]
Hi, thank you for the response.

The url of the room should be:
https://blinest.com/rooms/1-billion-streams-spotify
This link brings me to the general room.

The only link that works is this one:
https://blinest.com/rooms/39202
But it is only accessible by clicking on ''my account''.

Thank you!

**Comment by mchev** [comment]
Fixed [3279009](https://github.com/mchev/blinest/commit/32790097cfc2f6fc3ec95cb0354a190b18717177)

**Comment by Mishatje** [comment]
Thank you!
