### ISSUE TITLE
Sound

### ISSUE THREAD

**Issue by NonoBooo** [mchev/blinest#17]
I don’t have any sound in blinest.com

**Comment by mchev** [comment]
Hi,

Are you using an Iphone? If so, there is actually an issue with some apple devices. 
It is also possible to play with the volume button in the answer bar.

**Comment by mchev** [comment]
Should be fixed in [b26c185](https://github.com/mchev/blinest/commit/b26c1858e640b9d3b5e50e392200183241e0183f)

**Comment by mchev** [comment]
Fixed by 937be3d
