### ISSUE TITLE
Broken rankings page

### ISSUE THREAD

**Issue by Thithic** [mchev/blinest#18]
Hello, 
La page de ranking semble inatteignable (chargement infini) [https://blinest.com/rankings](https://blinest.com/rankings)

**Comment by mchev** [comment]
Fixed in a02ecaf and 761cca6

**Comment by Thithic** [comment]
Thank you !

**Comment by mchev** [comment]
Reopen - performance issue

**Comment by mchev** [comment]
New table with total scores for better performances and new page. https://blinest.com/rankings
