### ISSUE TITLE
import playlist Spotify 

### ISSUE THREAD

**Issue by sylvainar** [mchev/blinest#21]
Bonjour,

Merci pour votre travail sur la v2, c'est super beau ! Par contre on ne retrouve pas le bouton pour importer une playlist Spotify, la fonctionnalité n'est plus disponible ?

**Comment by mchev** [comment]
Bonjour,

La fonctionnalité à été retirée depuis la v2 car elle n'était pas stable. Il est prévu de remettre ça en place dans d'ici janvier.

**Comment by mchev** [comment]
L'import de playlist est de nouveau possible.
