### ISSUE TITLE
Proposition pour les Scrollbar

### ISSUE THREAD

**Issue by JuReyms** [mchev/blinest#22]
::-webkit-scrollbar {width:5px;}
::-webkit-scrollbar-track {rgb(23 23 23/var(--tw-bg-opacity));}
::-webkit-scrollbar-thumb {background-color: rgb(13 148 136/var(--tw-bg-opacity));}

**Comment by mchev** [comment]
Bonjour,

Quel est le problème avec les scrollbar?

Pour proposer une modification de code, merci d'ouvrir une Pull Request.
