### ISSUE TITLE
Playlists

### ISSUE THREAD

**Issue by Kiitysha** [mchev/blinest#23]
Bonjour, 

Nous ne pouvons plus créer de playlists sur votre site possible de fixer le bug ? 

Merci beaucoup

**Comment by mchev** [comment]
Bonjour,

La création de playlist semble fonctionner correctement.
Est-il possible d'envoyer une capture d'écran du message d'erreur?

**Comment by Kiitysha** [comment]
Bonjour :)

Voici le screen en PJ.
Merci beaucoup

**Comment by mchev** [comment]
Fixed in ebddd9f
