### ISSUE TITLE
La création de Room renvoie une erreur 404 (non bloquante)

### ISSUE THREAD

**Issue by Ckrapock** [mchev/blinest#29]
- Aller dans Rooms
- Entrer un nom
- Cliquer sur Create Room

Résultat : 
Une erreur 404 apparait (screenshot). La room est quand même créee et on peut y accéder par la recherche et l'utiliser normalement après cela.

Attendu:
Juste enlever l'erreur 404, possiblement beaucoup de gens pourraient croire que la room n'est pas créée.

![image](https://user-images.githubusercontent.com/125498940/219142021-ae047f87-f4cf-4213-9618-5933f70c3fcd.png)

**Comment by mchev** [comment]
Fixed by 80ec694

**Comment by Ckrapock** [comment]
Thanks @mchev
