### ISSUE TITLE
Pouvoir passer sa playlist dans l'ordre de création des morceaux

### ISSUE THREAD

**Issue by Ckrapock** [mchev/blinest#30]
Une fonctionnalité qui a été perdue avec la nouvelle version : 

- La capacité de jouer une playliste dans l'ordre de création des morceaux
- La capacité de commencer à jouer une playlist à partir d'ou on veut, par exemple juste les derniers morceaux créés.

Importance : on peut s'en passer mais je sais que certains utilisateurs regrette cette fonctionnalité (Emma en tête). Ca permettrait de ne passer que les fins de liste pour juste jouer les titres les plus récents rajoutés uniquement par exemple.

Pourrait être un choix au niveau de la room. 

- [Ordre des titres] : Aléatoirement(défaut)/Dans l'ordre
- [Jouer les titres à partir de] : [numéro] (par défaut, 1) -> Numéro de morceau ) partir duquel la playlist part. Uniquement visible et sélectionnable si [Jouer les Morceaux] = Dans l'ordre. Lorsque la playliste passe s'il ne reste pas assez de morceaux, arrivé au dernier, s'arrêter. Exemple : J'ai 30 morceaux dans ma playlist au total, ma room possède 20 morceaux à jouer, je sélectionne de les jouer dans l'ordre, arrivé à 10 morceaux, je m'arrête.

OK... maintenant, le cas ou il a plusieurs playlists associées à une même room...
Si [Ordre des titres] = Dans l'ordre, c'est l'ordre de l'association des playlists qui va compter. A l'utilisateur de changer en fonction de ce qu'il veut passer.
 [Jouer les titres à partir de] sera le numéro de chanson toute playliste confondue. Playlist 1 a 10 morceaux, Plalist 2 a 20 morceaux. Si  [Jouer les titres à partir de] = 15, c'est à partir du 5ème titre de Playlist 2 que ça va partir.

**Comment by mchev** [comment]
Random checkbox added in rooms options. The ability to manually choose the order of the tracks will not be implemented.

**Comment by Ckrapock** [comment]
That's great and some people will be happy about it! thanks @mchev you rock!
