### ISSUE TITLE
Categories names translation

### ISSUE THREAD

**Issue by Ckrapock** [mchev/blinest#36]
**Page principale**
Musical Genre
Decades
On Screen

![image](https://user-images.githubusercontent.com/125498940/219478313-32d02828-f0fd-44f5-a376-514a7435aa21.png)

**Comment by Ckrapock** [comment]
ChatGPT propose de faire ce genre de code pour internationaliser les libellés dans `CategorieSeeder.php`, mais étant donné que je ne sais pas comment lancer l'app pour faire des tests, je préfère te laisser juge
```
<?php

namespace Database\Seeders;

use App\Models\Category;
use Illuminate\Database\Seeder;

class CategoriesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $genre_musical = _('Genre musical');
        $les_decennies = _('Les décennies');
        $sur_les_ecrans = _('Sur les écrans');
        $divers = _('Divers');
        
        Category::factory()->create([
            'name' => $genre_musical,
        ]);
        Category::factory()->create([
            'name' => $les_decennies,
        ]);
        Category::factory()->create([
            'name' => $sur_les_ecrans,
        ]);
        Category::factory()->create([
            'name' => $divers,
        ]);
    }
}
```

**Comment by mchev** [comment]
Bonjour, je regarderais pour rendre traductible les noms de catégories.
Dans tous les cas il vaut mieux ne pas utiliser chatGPT pour ce type d'usage, ce qu'il propose n'a aucun sens.

**Comment by Ckrapock** [comment]
Thanks you Sir !
