### ISSUE TITLE
User can't change the room picture even if the conditions are met.

### ISSUE THREAD

**Issue by Ckrapock** [mchev/blinest#37]
J'ai une image png que j'uploade sur une room
A la mise à jour, erreur 500
![image](https://user-images.githubusercontent.com/125498940/219687232-71a9f5d6-a9cc-4df9-b242-29389d997205.png)

Puis ce message 
![image](https://user-images.githubusercontent.com/125498940/219687354-60214128-2b91-48a9-a1c0-2d1d9ddd758b.png)

**Comment by Numb25** [comment]
idem - j'ai essayé d'uploader une photo avec les formats indiqués et j'ai l'erreur 500 SERVOR ERROR au moment de la mise à jour.

**Comment by mchev** [comment]
Est-ce que c'est toujours valable? J'ai modifié pas mal de trucs depuis l'ouverture de cette issue.

**Comment by Ckrapock** [comment]
Pour ma part, j'ai ce message d'ancienneté donc je n'ai pas accès au bouton d'upload... 
![image](https://user-images.githubusercontent.com/125498940/227601713-b338bd14-37d1-45c4-8e84-9d60fc799d38.png)

**Comment by Numb25** [comment]
Même message pour moi

**Comment by mchev** [comment]
Le message est normal, ce n'est pas une erreur. Je n'ai pas eu d'autre retours concernant l'upload de photos (mail ou discord). Je close pour le moment et rouvrirais si on me fait des retours.

**Comment by Ckrapock** [comment]
Je proteste amicalement :)

> 3 mois d'ancienneté et > 2000 points !

![image](https://user-images.githubusercontent.com/125498940/227611264-40e3c6d4-1c63-436f-82ae-efc79334f8dc.png)

**Comment by mchev** [comment]
Ah ok, c'est un autre problème ça.
J'ai modifié le titre pour que ce soit plus clair pour moi.
@Ckrapock vu que tu m'aide beaucoup ces temps-ci sur le dev. Si tu le souhaite on peut prendre 5 minutes pour que tu ai un environnement local de tests/code pour éviter les PR "à l'aveugle". Si tu as discord contacte moi dessus.

**Comment by Ckrapock** [comment]
Dis moi si tu veux un autre fiche ou si on garde celle là

**Comment by Ckrapock** [comment]
Ce serait super. J'ai essayé plusieurs fois dans codespace mais pas réussi. Je te contacte dans discord, mais je veux surtout pas te prendre trop de temps vu le peu de compétences que j'ai, je m'imagine pas faire des miracles même avec un environnement de des, c'est pour ça que j'ai pas insisté. Enfin on va essayer quand meme ! :)

**Comment by Ckrapock** [comment]
_Back to the topic, je suspecte grandement que le problème est lié au comptage de points/ancienneté pour les anciens utilisateurs d'avant la migration v2. Mes observations:

- Tous les anciens utilisateurs d'avant v2 ont le message : Numb, Dudule, Jul, moi etc... 
- Les nouveaux utilisateurs d'après v2 (et qui rentrent dans les critères) peuvent uploader : le cas d'Emma qui a (re)créé un compte après la v2 et j'ai vu qu'elle avait réussi à actualiser des photos.

La possible enquête de ton côté : comparer les critères points et ancienneté entre le compte Emma Webster versus mon compte (ou un des autres cités plus haut) par exemple._

ERRATUM : En fait Emma n'a pas changé les images de ses plays. J'ai cru mais c'est juste qu'elle a mis un emoticon en titre et ça m'a mis dans la mauvaise direction... du coup je ne suis pas sûr que ce soit un probleme d'avant/après migration. Désolé.

![image](https://user-images.githubusercontent.com/125498940/227721197-027008f7-54f6-4b44-82a3-bfe59d2b6c23.png)

**Comment by mchev** [comment]
Fixed

**Comment by Ckrapock** [comment]
Merci @mchev je confirme que ça marche nickel pour moi !
