### ISSUE TITLE
Rajout de langue ?

### ISSUE THREAD

**Issue by Ckrapock** [mchev/blinest#38]
Je serais grave chaud pour rajouter des langues. Qu'en penses-tu ?
J'avais pensé à
- L'allemand pour les raisons suivantes : il me semble que les allemands raffolent de ce genre de jeux + J'ai commencé à faire un fichier de.json (vu que je suis bidon chatGPT est mon ami mais est un peu lent, mais on peut y arriver... par contre on aura pas grand monde pour vérifier/corriger dans un premier temps, à part mon faible niveau de langue)
- Le portugais car on a Juliano qui pourrait aider à faire le fichier et/ou vérifier, et éventuellement accueillir des lusophones

Après je comprendrais que ne maitrisant pas les langues il puisse y avoir les problèmes légaux (?), ou alors une maintenance plus compliquée (?), performances moindres (?).... du coup je comprendrais aisément que tu ne veuille pas. Un avis?

**Comment by Ckrapock** [comment]
Bon j'étais un peu chaud et j'ai rajouté le contenu pour le portugais et l'allemand dans la pull request https://github.com/mchev/blinest/pull/35
Tu es toujours en droit de la refuser, et j'imagine que pour les activer il y a un autre truc à faire mais je suis pas bien sûr.
Si tu acceptes je m'occuperai après des ajustements lorsque je pourrai vérifier sur écran!

Edit : actualisation linguistique et rajout des libellés d'erreur/succès dans https://github.com/mchev/blinest/pull/35/commits/b68b2641d342a9a302e6babb960f8a1d1123bb9c

Les choix linguistiques sont les suivants, un peu arbitraires mais si feedback je peux changer.

**Allemand**
"Room" : Choix de laisser "Raum" pour Room car j'imagine que les sonorités approchant, ça ferait bizarre en allemand
"Playlist" ok utilisation de "Playlist" (qui est de toute manière l'usage courant)
"Team" ok utilisation de "Team" (qui est de toute manière l'usage courant)

**Portugais** - quelques changements
"Room" : choix d'utilisation de "Room" au lieu de "Sala", pour faire comme en français. Mis au féminin.
"Playlist" : ok utilisation de "Playlist", quelques changements effecuté.
"Team" : choix d'utilisation de "Team" au lieu de "Equipo", pour faire comme en français. Mis au féminin.
Si ça choque Juliano on pourra changer.

**Comment by mchev** [comment]
La traduction du site dans d'autres langues n'est pas une priorité car les extraits audios ne sont disponibles que sur le marché français. Pour le moment pas de solutions pour permettre aux joueurs Américains/Allemands/etc. de jouer avec des européens en même temps sur les mêmes extraits.

**Comment by Ckrapock** [comment]
D'accord pas de problème ! Je garde cependant l'Allemand et Portugais de côté si jamais tu changes d'avis !
