### ISSUE TITLE
Internationaliser les méta données pour les recherches web

### ISSUE THREAD

**Issue by Ckrapock** [mchev/blinest#39]
Par exemple je suis connecté en anglais , et google me renvoie la meta donnée en français (même chose pour les meta twitter et FB)

![image](https://user-images.githubusercontent.com/125498940/219943977-70d090e7-9d96-45ee-9428-4f7a73886167.png)

Le contenu est dans AppLayout.vue et dans Index.vue, mais sur le coup je ne suis pas entièrement sûr de savoir le faire sans bêtises.

Si tu me mets sur la voie (structure générale pour l'anglais par example), je m'occuperai du reste.

**Comment by mchev** [comment]
L'internationalisation n'est pas la priorité. Les extrais audios étant restreints au marché français il n'est pas nécessaire d'aller plus loin pour le moment.

**Comment by Ckrapock** [comment]
Entendu!
