### ISSUE TITLE
Translations issue (round 2)

### ISSUE THREAD

**Issue by Ckrapock** [mchev/blinest#46]
After Issue https://github.com/mchev/blinest/issues/34 was merged. 
New round of translations - PR opened : https://github.com/mchev/blinest/pull/47

List spotted

**Individuals**
- La page d'édition de la room (page mot de passe) -> little issue in sentence both Fr and EN 
- Modos - to be translated in EN by "Mods" 
- Inutile d'envoyer les suggestions séparement -> to be internationalised 
- Attention, cette fonctionnalité n'est à utiliser qu'en cas de problème de respect des règles sur le chat ou d'une panne sur la partie -> to be internationalised/translated 
- Commentaire (facultatif)  -> to be internationalised/translated
- Une idée? 
- Public rooms not translated in French 
- Send by -> change into "Sent by" 
- Les titres en doublon ne seront pas importés.
- Pour importer une playlist, celle-ci doit être publique.<br />Les extraits ne pouvant pas être lus par le site ne seront pas importés.OK
- Previous Team list 
- Next team list
- Invites tes amis en privé, ou partage tes playlists...

**Files**
- all labels at Banned.vue
- all labels at ImportPlaylist.vue
- All labels in PlaylistImport like .vue files

**Comment by Ckrapock** [comment]
@mchev la PR est ouverte pour ci-dessus.
**Non inclus** : les libellés de popup, car je n'étais pas sûr...
Par exemple:
`if (confirm('Voulez-vous vraiment supprimer cet extrait?'))`
Est-ce que c'est sans risque de le changer par 
`if (confirm(__('Do you really want to delete this track?'))`

**Comment by mchev** [comment]
> @mchev la PR est ouverte pour ci-dessus. **Non inclus** : les libellés de popup, car je n'étais pas sûr... Par exemple: `if (confirm('Voulez-vous vraiment supprimer cet extrait?'))` Est-ce que c'est sans risque de le changer par `if (confirm(__('Do you really want to delete this track?'))`

Effectivement les traductions ne fonctionnent pas dans les fonctions confirm() et alert()

**Comment by Ckrapock** [comment]
Tant pis ça restera en français. J'ai corrigé pour l'erreur de syntaxe, le paragraphe au milieu de là ou ça devvrait pas être,  updatédans la PR actuelle

**Comment by mchev** [comment]
#47
