### ISSUE TITLE
Improve/Change messages when the user is right/almost/wrong

### ISSUE THREAD

**Issue by mchev** [mchev/blinest#48]
To make the short messages that appear when you type a reply more universal and sometimes less aggressive, it would be good to review the formulations and why not add new ones. The English and French versions do not necessarily have to be identical as the expressions may vary from country to country.

**Comment by Ckrapock** [comment]
@mchev despite the fact that I loved the fact to keep "faut pas pousser mémé dans les orties" identical in English :), I can propose a softened version of these, open a PR and then you'll decide.
Just confirm and i'll go ahead.

**Comment by mchev** [comment]
If you've got ideas for this, go for it 👍

**Comment by Ckrapock** [comment]
Hop let's go. Pull request https://github.com/mchev/blinest/pull/49
Summary
FR : removed most aggressive "bad" messages, and softened overall. Removed idiomatic ones.
EN : currently pure translation of the FR one
Let me know any changes to do!

**Comment by mchev** [comment]
Closed #48.
Thanks 😊
