### ISSUE TITLE
Spotify playlists not importing all the way 

### ISSUE THREAD

**Issue by Hockawr** [mchev/blinest#5]
Firsts of all, I love the site and especially the private game feature. But when I try to create my private games by importing a spotify playlist, only a portion of it truly imports. For example while importing this playlist (https://open.spotify.com/playlist/37i9dQZF1DX7LGssahBoms?si=59b38e5e4c954020), containing  70 tracks, the system imports only 30.

**Comment by mchev** [comment]
Hi, this can happen for several reasons.

- Some imported songs are already in the playlist
- The imported tracks do not have 30 seconds samples available on the French market. (the site checks if the extract is available before the recording in database)
- The playlist is not public

If the script crashes the console should return a 500 error.
If not, please share more information (console feedback, error, etc)
