### ISSUE TITLE
Access to "My account" leads to error 500

### ISSUE THREAD

**Issue by Ckrapock** [mchev/blinest#51]
When accessing my account (https://blinest.com/me)

After checking around with asking on a room, depends on users.
- Numb and myself : error 500 - personally using chrome if that matters. I also tried emptying my caches, no luck.
- Mikajo, Speedy, Sop, Imala : was ok.

![image](https://user-images.githubusercontent.com/125498940/221994054-529cb768-808b-4b64-9de5-8a191776401a.png)

**Comment by mchev** [comment]
For the moment, I can't reproduce this error. Is it still not wroking for you?

**Comment by Ckrapock** [comment]
Works now... go figure :) 
Closing!
