### ISSUE TITLE
Translations/label issues (round 4 - adjustments)

### ISSUE THREAD

**Issue by Ckrapock** [mchev/blinest#53]
I'll handle when a reasonable number of changes to do is spotted.

Voule**s**-vous vraiment supprimer cette room ?
'error', 'Le mot de passe est incorrect.') -> to be internationalised (although for other "errors" being done, the content always appears in English... probably syntax to adapt, but at least everything will be aligned)

Issues from my last commit:
"Creation:":"Cr**e**ation :", -> Cr**é**ation
 "Suppression:":"Deletion :", -> Invert and check where deletion is used.

Testez votre culture musicale

Some internationalisations into user management page.

**Comment by Ckrapock** [comment]
PR opened : https://github.com/mchev/blinest/pull/54

**Comment by mchev** [comment]
Merged #54 
No need to create an issue for each PR.
Just to be more readable in long term, try to use better commit message explaining what you are doing in the commit.
Thanks for all the work on translations

**Comment by Ckrapock** [comment]
You're welcome, happy to help.
OK for next time i will not create an issue.
For commit message, ok i'll put everything inside it (even if it will go over the 25-30 characters allowed in title, but I guess it can be seen anyway somehhow)
