### ISSUE TITLE
When posting a message in the chatbox, the last line is hidden

### ISSUE THREAD

**Issue by Ckrapock** [mchev/blinest#55]
Once first page is filled in messages, when posting myself, or other who post, the last line is not visible

![image](https://user-images.githubusercontent.com/125498940/223554863-efe39991-2878-4f92-9724-a023ee02f843.png)

It's annoying as we have to scroll to see the latest message each time something is posted.

After asking around, it seems:
- Chrome & Opera : issue is there
- Firefox : no issue

**Comment by mchev** [comment]
Fixed [056ad9f](https://github.com/mchev/blinest/commit/056ad9f6cfac8c07df2f211749ce6d995d4bcd82)

**Comment by Ckrapock** [comment]
Quickly checked, seems to be working awesome thanks @mchev !!! this one is a relief :)

**Comment by Ckrapock** [comment]
Hey @mchev after a bit of talking in a chat the problem reappeared

Seeing your previous commit, maybe when above 5000 [whatever this scrollheight is?], because we started the chat and it was ok for like 10mn chatting before the problem happened.

![image](https://user-images.githubusercontent.com/125498940/226720847-3ea84fda-83ff-428c-91ed-847f9c605dbc.png)

From asking around in this chat
Chrome/Edge : issue there
Bing : no problem.

**Comment by mchev** [comment]
To check before close.
[e739777](https://github.com/mchev/blinest/commit/e73977703850841061b928bacd977bb1890fde84)

**Comment by Ckrapock** [comment]
Won't be able today but i have been asking 6 or 7 people to check.
If they don't respond i'll probably play tomorrow and confirm!

**Comment by Ckrapock** [comment]
I finally just played during a little bit and I can confirm from me and other users that problem has totally disappeared!!!
Thanks again @mchev, in the name of everyone!!!!!

**Comment by Ckrapock** [comment]
OK... I did back and forth if you see your notifications, but at the very end, the problem still appears for me at some point... 
Way less than before and to be honest, I cannot identify in which case it appears... possibly when updating the room options during the game, like the autostart, but honestly could not be sure... so i'll leave this one closed to avoid headaches on your side, until i really find the exact use case (unless you have an idea with the code, but don't bother!)

**Comment by Ckrapock** [comment]
@mchev I have found a scenario to reproduce finally!!!

I'm Chrome.
Have a chat window where people have talked a lot so to fill the page.
If I type something it works all ok... until 
I move the right bar up and put it back down like this

Up 
![image](https://user-images.githubusercontent.com/125498940/227389346-0c09f5b9-4f65-474e-b16c-483ee1344c96.png)

And back down
![image](https://user-images.githubusercontent.com/125498940/227389409-2aa0359e-eb9a-4c1e-828a-2cd4f9a0f475.png)

Then at this point I get the issue again, despite i'm positioned down the chat.

A workaround : click twice on the chat button to make it disappear/reappear and that initialises the chat and problem gone until i touch this vertical bar again.

**Comment by Ckrapock** [comment]
Cool ! I'll test & confirm tonight when i have played a bit with other players!
UPDATE : confirmation that it works fine! Haven't tested myself but dudule confirmed. Awesome!
