### ISSUE TITLE
System of favourite rooms

### ISSUE THREAD

**Issue by Ckrapock** [mchev/blinest#56]
Some people would like to see a system to bookmark favourite rooms, as sometimes they wouldn't remember a nice room they played on.

Maybe a system to bookmark a room -> then the list would appear in a menu (main page or "my account")
And then capability for user to add their own personal comment to remember exactly what the room was about.

If not in the roadmap no problem, please close it, just being the messenger there! 
As a workaround, I just advised to add their favourite rooms in browser bookmark :)

**Comment by mchev** [comment]
Done 9256ea1

Future improvements :
- Bookmarked rooms on homepage
- Ordering by bookmarks count
- Notify owner on the room
- Display total bookmarks by rooms

**Comment by Ckrapock** [comment]
Wow faster that a shark, thanks @mchev , some will be happy!
