### ISSUE TITLE
Importer playlist exporté depuis blinest

### ISSUE THREAD

**Issue by Tasye24** [mchev/blinest#58]
Est-ce possible d'importer un fichier qu'on a préalablement exporté ?
![image](https://user-images.githubusercontent.com/51138405/224818332-b61e7d39-33ae-48cb-a2c3-cc0038c4c157.png)
![image](https://user-images.githubusercontent.com/51138405/224818674-99b2339e-a4e8-4f52-a3f2-422da527ff9e.png)
(idée non actuel)

**Comment by mchev** [comment]
Quel est l’intérêt puisque la playlist existe déjà ?

**Comment by Tasye24** [comment]
@mchev Ducoup ca aurait pour compenser le fait de ne pas pouvoir si on été modo et le fait de pouvoir exporter sans importer c'est dommage mais si on peut en changer la propriété ca le fait.
