### ISSUE TITLE
Associer une playlist où on est modérateur

### ISSUE THREAD

**Issue by Tasye24** [mchev/blinest#59]
On ne peut pas ajouter une playlist pour laquelle on est modo

**Comment by mchev** [comment]
Bonjour, je ne suis pas bien sur de comprendre le problème. Est-il possible de détailler un peu plus?

**Comment by Ckrapock** [comment]
Je confirme, et précisions en même temps pour @mchev :
Le principe est que tu peux associer les playlists sur lesquelles tu es **propriétaire** seulement, et pas modérateur en attendant un éventuel fix, donc l'astuce à faire que j'avais trouvé avec d'autres:
- Demande au propriétaire de la playlist dont tu es modérateur de te mettre toi-même propriétaire. A priori tu le connais vu qu'il a dû te mettre modérateur à un moment ou un autre.
- Crée ta room et associe cette playlist.
- Ensuite, pour être clean, rechange la playlist et redonne la à son propriétaire initial.

J'imagine qu'il faut rajouter la condition isRoomModerator dans plusieurs endroits sur les fonction attach et detach...
Si j'osais je tenterais bien une PR... mais comme je ne peux pas tester je préfère jouer l'humilité et m'abstenir de faire pleins de bêtises sur le coup!
![image](https://user-images.githubusercontent.com/125498940/224864639-1f8e7617-cec5-4094-ae80-85c206a2c137.png)

**Comment by Tasye24** [comment]
Merci pour la réponse @Ckrapok ca à marché comme ca

**Comment by mchev** [comment]
Je laisse ouvert cette issue, car c'est effectivement quelque chose à améliorer plutôt que de bidouiller pour y arriver.
C'est dans le programme de développement pour fin mars début avril.

**Comment by Ckrapock** [comment]
Bidouilleur un jour, bidouilleur toujours !

**Comment by mchev** [comment]
Fixed [390a41f](https://github.com/mchev/blinest/commit/390a41fb3cd171dae96b6230f3355d6c5c6319ad)
Les modérateurs de playlists peuvent maintenant associer les playlists qu'ils modèrent à leurs rooms.

**Comment by Ckrapock** [comment]
Ce backlog killer! gg @mchev 




J'ai testé avec un cas réel que j'avais, et je mets ici les problèmes que j'ai chez moi.

Important : il semble que les problèmes ci-dessous ne soient que chez moi. Dudule n'a pas ces problèmes. Je suis sur Chrome il est sur Opéra si ça a un impact...
@Tasye24 si jamais tu peux confirmer chez toi ce que ça donne?

1 - Dans mes rooms Je n'arrive pas à accéder à la playlist "La Bamboche" sur laquelle je suis modérateur mais pas propriétaire. Elle n'est pas dans ma liste.
J'arrive à y accéder par le biais de "Mon compte"  ceci dit, comme ci-dessous.


![image](https://user-images.githubusercontent.com/125498940/226423031-c606c7fc-3214-4e6b-b9c4-5e47fb679214.png)

Possiblement pas lié complètement à ce problème initial ceci dit.

2 - A partir de là, quand je veux attacher à "La Bamboche une la playlist "Inclassable" dont je suis modérateur mais pas propriétaire

- Je vois bien la play dans les play à associer
- Mais à la fin j'ai un "unauthorized action" à la validation
- Même résultat quand j'essaie d'en dissocier une de cette même room. Sur mes room pas de pb.
![image](https://user-images.githubusercontent.com/125498940/226423807-51db0b3b-d055-4f53-9a2e-f3c54b199d92.png)

Analyse...
J'ai supprimé la room la Bamboche (je n'en était pas le créateur initialement). Je l'ai recréée en "la Bambocha" et associé les mêmes playlists et je n'ai plus de problèmes.
PAR CONTRE, maintennat c'est Dudule qui a exactmement les mêmes problèmes que ci-dessus.
Donc je pense que si on est **créateur** de la **room** pas de problème, mais si on n'est que **modérateur** là les trucs bizarres se produisent.

**Comment by mchev** [comment]
Un modérateur de room n'a pas la possibilité d'associer ou dissocier les playlists sur la room. Seul le propriétaire de la room a ces droits.
Les rooms modérées apparaissent maintenant aussi sur la homepage dans "Mes rooms"

**Comment by Ckrapock** [comment]
Ah d'accord merci @mchev c'est noté.
J'ai une dernière demande (pas du code). Est-ce que tu pourrais restaurer "La Bamboche" ? Dudule est malheureux depuis que je l'ai supprimée :)

**Comment by mchev** [comment]
> J'ai une dernière demande (pas du code). Est-ce que tu pourrais restaurer "La Bamboche" ? Dudule est malheureux depuis que je l'ai supprimée :)

Malheureusement ce qui est supprimé, l'est pour de bon.

**Comment by Ckrapock** [comment]
Pas grave. Juste une question @mchev  : hier j'avais essayé de recréer "La Bamboche" mais je n'y arrivais pas car le nom existait déjà. Là j'ai réussi. Au bout de combien de temps suis-je capable de recréer une room supprimée avec le même nom ? J'imagine qu'il y a un batch qui passe pour supprimer les room définitivement... genre une fois par jour ?

**Comment by mchev** [comment]
> J'imagine qu'il y a un batch qui passe pour supprimer les room définitivement... genre une fois par jour ?

Tous les jours à 7h du matin.

**Comment by Ckrapock** [comment]
> > J'imagine qu'il y a un batch qui passe pour supprimer les room définitivement... genre une fois par jour ?
> 
> Tous les jours à 7h du matin.

Impeccable, merci pour l'info !
