### ISSUE TITLE
Possible to have rooms sorted by number of players ?

### ISSUE THREAD

**Issue by Ckrapock** [mchev/blinest#68]
I'm logging that one on behalf of Numb (she should have an account in github as she posted once but cant find it...)

In the index page, the sorting of the rooms is strange to us to understand. Is there a current logic ?

**The issue:**
In some case, in order to find some rooms with more than 0 players, it's needed to click on the right side arrow and sometimes played rooms can be far away scrolling.
![image](https://user-images.githubusercontent.com/125498940/227370457-3173f364-c661-4697-9edf-f23afc9ae091.png)

Numb also says sometimes a private room where people are playing is not even displayed. I personally haven't noticed that.

Possible change ; would it be possible to sort the rooms by number of players, with the most attended room appearing on the left?

**Comment by mchev** [comment]
To improve page load performance, the list of the rooms in the homepage is cached. The list is updated every 2 minutes.

**Comment by Ckrapock** [comment]
Awesome and I observe that the update was longer before so that would explain why Numb didn't see rooms sometimes, and that now it will still happen but a bit less.
For the sorting i'll confirm for good tonight when more players will be online, but already that looks quite ok!

UPDATE : looks great with all categories have their rooms sorted, thanks a lot!
