### ISSUE TITLE
Functional messages popups don't stay visible long enough

### ISSUE THREAD

**Issue by Ckrapock** [mchev/blinest#70]
This one as the example

![image](https://user-images.githubusercontent.com/125498940/227606389-f712f463-f988-4e19-9bf2-79df318d1ca3.png)

The red popup stays visible like less that 1/2 second, which is not possible to read well for new users.
Probably go back as it was previously where it just didn't disappear, until the user clicks the close button?
Also, I believe having them centered was quite nice than on the right side (but that's a matter of taste here maybe...)

**Comment by mchev** [comment]
This actually doing that when you try a lot to test the site :) The popup is normally staying around 2 seconds.
For the position this is the best place considering this can also be displayed a lot for moderators while playing. For regular users this kind of popups are almost not used.

**Comment by Ckrapock** [comment]
Haha yes i'm try harding there :)
Let's close this then!
