### ISSUE TITLE
Room creation not attaching automatically the owner as moderator

### ISSUE THREAD

**Issue by Numb25** [mchev/blinest#75]
Bonsoir, lorsqu'une room est créée sans modérateur (par oubli), est-il possible d'ajouter un modo par la suite (pour le coup, moi, Numb)? 
En l'occurrence, il s'agit des salles MDNA true blue et MDNA into the groove. 
Sorry et merci d'avance :(

**Comment by Ckrapock** [comment]
Discuté avec Numb sur le chat, effectivement quand une room est créée en oubliant de se mettre en modo (ce qui est le cas la plupart du temps), il est impossible de la retrouver dans "mes rooms" ou dans "mon compte", et dans ce cas la room est perdue. 

Je pense qu'on va tous tomber dans le panneau en oubliant de se mettre modérateur :) 

Il s'agit d'une régression récente (possiblement https://github.com/mchev/blinest/issues/59 ?) car avant ces rooms sans modérateurs étaient accessibles en tant que propriétaire.

**Comment by mchev** [comment]
Le créateur de la room est automatiquement modérateur de celle-ci désormais. 
https://github.com/mchev/blinest/commit/edd6aecd7122a1729212d0e55fa01a2f90953bbc#diff-0ff33021e4fca96797d067a9e8aff79081b4d0214ba3520e0bfab45a61a43ad5

**Comment by Ckrapock** [comment]
Testé vite fait ça marche super, merci @mchev !!!
Le seul cas possible qui pourrait cause probleme : un créateur de room retire son nom de la modération de la room (sans transférer à quelqu'un), et là sans id la room est "perdue"... mais honnêtement ce cas devrait ne jamais se produire, ou au pire une fois tous les 36 du mois, donc c'est nickel comme ça !

**Comment by mchev** [comment]
> Testé vite fait ça marche super, merci @mchev !!! Le seul cas possible qui pourrait cause probleme : un créateur de room retire son nom de la modération de la room (sans transférer à quelqu'un), et là sans id la room est "perdue"... mais honnêtement ce cas devrait ne jamais se produire, ou au pire une fois tous les 36 du mois, donc c'est nickel comme ça !

Si le créateur se retire de la modération, il verra toujours la room dans sa liste (via le menu mes rooms). Il pourra ensuite se re-assigner en tant que modérateur.
