### ISSUE TITLE
"Quiz général" ranking takes forever to load

### ISSUE THREAD

**Issue by Thithic** [mchev/blinest#76]
Hello, 
Le classement du quiz général est devenu impossible à voir. 
C'est un problème qui s'est amplifié récemment, et qu'on peut retrouver dans d'autres rooms.
Le temps de chargement des classements semble dépendre de la "popularité" des rooms : 
- room privée : chargement instantané
- années 90 : dizaine de secondes
- général : ♾️ 

Bonne journée ! :)

**Comment by mchev** [comment]
Done. 
- Rooms scores are now cached for 10 minutes.
- DB ans indexes edited. 
- 30 days history removed to prevent unecessary long queries.
- queries refactored
