### ISSUE TITLE
Profile pictures not showing anymore

### ISSUE THREAD

**Issue by Thithic** [mchev/blinest#77]
Hello, 
Les photos de profils n'apparaissent plus comme avant : 
- dans le chat
- dans le classement (/rankings)
- sur le "podium" à la fin des parties

Bonne journée, et merci pour ton travail :)

**Comment by mchev** [comment]
Le problème est réglé. Merci pour le retour

**Comment by Thithic** [comment]
Bonjour, 

Le problème a été réintroduit depuis quelques jours.

Bonne journée :)
