### ISSUE TITLE
Buggue d'accès profil

### ISSUE THREAD

**Issue by ghost** [mchev/blinest#78]
Bonjour,

Mon profil bugue, je ne peut accéder à mes informations et points gagnés, il m'est notifié erreur 500. Je peux toujours jouer sur les différentes room, me connecter et me déconnecter, accéder a ma room et à ma playlist.
Je me nomme K2B2.

Pouvez vous m'indiquer si cela est normal, quand cela pourrait être réglé, j'aimerais ne pas perdre mon profil.

En vous remerciant de votre réponse.

**Comment by mchev** [comment]
Bonjour,

Le problème devrait être réglé maintenant.
La page mon compte essayait d'afficher des scores d'une room qui avait été supprimée.

**Comment by ghost** [comment]
Merci beaucoup a vous cela fonctionne parfaitement.
Excusez moi du dérangement.
