### ISSUE TITLE
Search tracks by title does not return the most popular artist on top of the list

### ISSUE THREAD

**Issue by Ckrapock** [mchev/blinest#80]
This is a follow up of this one : https://github.com/mchev/blinest/issues/28

When searching a title in a playlist creation, most of the time the first artists shown are not the most obvious or popular

Example, I type in "Nothing else matters" and Metallica does not appear on the top of the list, but I have to scroll down to find it.

![image](https://user-images.githubusercontent.com/125498940/232145820-4912f74a-fd9e-4e5d-b8d7-75b828fd48ab.png)

If this was possible in this case to get the most popular artists on top, without losing benefits from your fix in https://github.com/mchev/blinest/issues/28 that would be great.

**_Note : If there's the least of a difficulty, feel free to close, this is really being picky from me :)_**

**Comment by mchev** [comment]
Results are now sorted by popularity for Deezer and Spotify but i don't have the info for Apple music.

**Comment by Ckrapock** [comment]
That works well when you type an artist first, but not just a title track, but no worries that's a possibly  hassle for little value there! Thanks a lot already!
