### ISSUE TITLE
amis sur la plateforme

### ISSUE THREAD

**Issue by elisavrl** [mchev/blinest#83]
Bonjour, j'aimerais savoir s'il serait possible un jour d'avoir des amis comme sur un réseau social sur blinest. 
J'espère que ce sera un jour possible :)

**Comment by mchev** [comment]
Bonjour,

Est-ce que tu as une idée précise de comment tu verrais ce système et ce que cela pourrait apporter?

Je ne comprends pas trop l’intérêt d'avoir un système de réseau social sachant que l'objectif du site est de participer à des blind-tests. Il y a déjà des chats dans chacune des rooms pour discuter avec tout le monde.

Au delà de ça il y a le Discord Blinest et bien sur tous les réseaux sociaux existants qui peuvent être complémentaires.

Le système de Team est déjà en quelque sorte un système "d'amis".

**Comment by elisavrl** [comment]
Bonjour, l'objectif serait de pouvoir avoir un chat privé avec un
autre joueur et de pouvoir se retrouver entre amis plus facilement.
Bonne journée à vous

**Comment by mchev** [comment]
> Bonjour, l'objectif serait de pouvoir avoir un chat privé avec un autre joueur et de pouvoir se retrouver entre amis plus facilement. Bonne journée à vous

Bonjour et merci pour le retour. Il n'est pas prévu dans les prochaines versions d'ajouter les chats privés. Cela laisse place à de nombreuses de dérives que je n'ai pas les moyens de contrôler à l'échelle de ce site.

Il existe plusieurs alternatives pour échanger entre amis :
- Créer une room privée protégée par mot de passe. Cela vous permet d'utiliser le chat entre vous même si ce n'est pas le but principal du site.
- Avoir un chat à coté (beaucoup de joueurs font ça) : Utiliser discord en même temps ou whatsapp ou twitch etc.

Bonne journée

**Comment by elisavrl** [comment]
Merci pour ces précisions.

**Comment by elisavrl** [comment]
Great!
