### ISSUE TITLE
Chansons qui "sautent" dans une room

### ISSUE THREAD

**Issue by Numb25** [mchev/blinest#88]
Dans la room Blue (https://blinest.com/rooms/12682), deux chansons se valident au lieu d'une. Une chanson passe, on répond et deux titres sont validés dans la playlist à gauche. Du coup les points font aussi n'importe quoi, ça se compte et se décompte.
Ce problème est souvent arrivé dans d'autres plays aussi peu avant la Noel mais je pensais que c'était réglé.
On est ressortis et après avoir joué ailleurs, quand on est revenus, le problème a disparu.
Merci d'avance.

**Comment by Numb25** [comment]
![Capture d'écran 2024-01-22 010907](https://github.com/mchev/blinest/assets/127801889/f60c5b6f-87c2-46ab-b5aa-9d5f145f2b25)

**Comment by Numb25** [comment]
dans l'image, c'est passé de fleetwood mac à tom jones, sans jouer les deux intermédiaires. Ca l'a fait dans plusieurs salles ce soir.

**Comment by Numb25** [comment]
ça l'a fait dans plusieurs salles ce soir

**Comment by Numb25** [comment]
Completed mais le bug existe toujours, pas spécialement dans ma salle :(
Apparemment c'est quand on entre dans une salle encore non ouverte en même temps ou plus ou moins.
Ici le cas dans la salle eurovision années 2000.
![Capture d'écran 2024-03-07 223329](https://github.com/mchev/blinest/assets/127801889/8bcac6c3-72ac-4fff-b655-eb35c12930b8)

**Comment by mchev** [comment]
Je laisse l'issue ouverte quelque temps encore, mais normalement le problème est réglé depuis aujourd'hui.

**Comment by Numb25** [comment]
Super Merci !
Pas encore pu tester mais d'avance merci :)

**Comment by sticmac** [comment]
Bonjour

Ce bug semble être revenu depuis au moins plusieurs semaines. Quand j'essaie de rejoindre une room avec des amis, quasi systématiquement, c'est comme s'il y avait plusieurs parties qui se lançaient en même temps et qui rentraient en conflit.
