### ISSUE TITLE
Add back the name of the Moderator in the room card

### ISSUE THREAD

**Issue by Numb25** [mchev/blinest#90]
We can no longer see the name of the moderator who created the room in the room card.  It becomes very difficult to know in which room we have to go, especially when there are a lot of rooms with similar names. (ex : generique serie tv or generiques series tv, which one is the one from Emma, for example ?)
Thank you !

![Capture d'écran 2024-01-09 001002](https://github.com/mchev/blinest/assets/127801889/7632509a-cd9d-4c3c-b621-fe069175f6ab)

**Comment by mchev** [comment]
Fixed in ba3b75a

**Comment by Numb25** [comment]
Thanks a lot !! :)
