### ISSUE TITLE
Add info about missing answers under the typing bar

### ISSUE THREAD

**Issue by HalibutGitWiz** [mchev/blinest#91]
When playing, you are usually watching the typing bar, to make sure you don't do a typo.
Under this bar, you can see which answers you got right, but not which ones are still missing.

For that, you have to look at the rankings, where you see grey labels like "Artist", "Title", "Featuring"... These labels are very useful for titles with more than the two usual artist + title answers.

It would be convenient if these grey labels also appeared under the typing bar, since that's were we're already looking !

**Comment by Numb25** [comment]
Not very useful to my opinion, if I may give it.

**Comment by mchev** [comment]
Maybe this should be put to a vote in the 'Suggestions' section on Discord to see if other users feel that it's necessary.

**Comment by HalibutGitWiz** [comment]
May I add that about 75% of the work is already done ? :smile: 
Under the typing bar, we already have a display of answers we got right.

![Screenshot_2024-03-05_09-31-39](https://github.com/mchev/blinest/assets/19535471/8a39faa2-d056-42ef-9493-4517147df9d2)

In the rankings, we have a similar visualization, but with both the answers we have and those we don't have yet.

![Screenshot_2024-03-05_09-31-53](https://github.com/mchev/blinest/assets/19535471/96ec6eab-5782-4809-8795-48b37f283a48)

What I'm asking, in this example, is simply to add a grey "Artist" box under the typing bar to inform me that I'm still missing the artist. Of course, it is obvious in that case, but that would be useful for multiple artists, musicals...

I suppose I feel that need because I usually play on a big screen. I may be in a niche use case. :wink:

**Comment by mchev** [comment]
Done
