### ISSUE TITLE
Remove yourself as moderator in private rooms

### ISSUE THREAD

**Issue by Numb25** [mchev/blinest#92]
Hello,
Once we have been added as a moderator of a private room, only the initial moderator (or room creator) can remove you from the moderator list.  
Is there a possibility to add a button to remove yourself from the moderation ? (in this case for example the initial moderator is no longer playing, for example)

![Capture d'écran 2024-02-14 014641](https://github.com/mchev/blinest/assets/127801889/1ea91cf4-2110-4937-adeb-1f8894e2bd83)

**Comment by mchev** [comment]
Done in [6302597](https://github.com/mchev/blinest/commit/6302597ba21e74e6e0cf92a2b12437378d3d3acd)

**Comment by Numb25** [comment]
Super, merci !
Could we apply this to the playlist as well ? 
Thaaaanks !
