### ISSUE TITLE
Search rooms by moderator name

### ISSUE THREAD

**Issue by Numb25** [mchev/blinest#93]
For now we can only do a room search by room name. On top of that, it would be a nice improvement to be able to do a search by Moderator name (the main moderator in case of several ones).

**Comment by mchev** [comment]
Good idea. Done :)

**Comment by Numb25** [comment]
Merciiiii :)



Envoyé depuis mon appareil Galaxy



-------- Message d'origine --------
De : mchev ***@***.***>
Date : 3/03/24 17:33 (GMT+01:00)
À : mchev/blinest ***@***.***>
Cc : Numb25 ***@***.***>, Author ***@***.***>
Objet : Re: [mchev/blinest] Search rooms by moderator name (Issue #93)


Good idea. Done :)
