### ISSUE TITLE
Import de Playlist Spotify & Deezer incomplet

### ISSUE THREAD

**Issue by lanc3lo1** [mchev/blinest#98]
Bonjour, bonsoir,

Je vous remercie tout d'abord pour votre travail, c'est un plaisir d'utiliser Blinest et ce depuis plusieurs années.

Lors de ma création de playlist j'ai tenté d'importer une playlist Spotify à moi qui comprend 983 titres.
J'ai pu constater qu'il faut faire plusieurs fois l'import pour voir les titres apparaître au fur et à mesure dans la playlist côté Blinest.
Mais je suis arrivé à un blocage lorsque j'ai atteint les 677/983 titres importés, j'ai beau tenté d'importer de nouveau ma playlist elle n'est pas importée en totalité malgré le flashbag de succès.
Je check les requêtes, tout a l'air de bien se passer de ce côté là, qu'en pensez-vous ?

![image](https://github.com/mchev/blinest/assets/25639103/f2a43ddc-b2dd-407d-8559-2d4337a74805)

Un ami développeur PHP

**Comment by mchev** [comment]
Bonjour et merci pour le retour,

L'import de playlist se fait en plusieurs fois (par paquet de 50 ou 100 extraits) afin de ne pas monopoliser le serveur pour un import trop large. Il faut attendre quelques minutes que toutes les tâches d'import soient effectuées.
Normalement en rafraichissant la page le nombre de titres devraient augmenter.
Si les extraits ne sont pas disponibles sur le marché français ou qu'une prévisualisation de 30 seconde n'est pas disponible pour un extrait, il ne sera pas importé. C'est surement pour ça que tous les extraits ne sont pas présents.
Il y aurait du boulot pour améliorer l'affichage des erreurs et la liste des extraits non importés. C'est dans la liste des choses à faire :)
Il est toujours possible de proposer une PR afin d'améliorer ça. Ce n'est pas dans les priorités pour le moment de mon côté.

**Comment by lanc3lo1** [comment]
Bonjour,

Merci pour la réponse, à l'occasion sur du temps libre j'essaierai de me pencher sur le sujet.

Bonne journée !
